# Update Hue lights after turning off
#
# Update Hue lights' turn-on brightness and/or color temperature when
# they turn off. This saves you from fumbling in the dark if a light was turned
# off by dimming to zero, or being dazzled after lights were last used on high.
#
# GET STARTED IN GUI:
#
# 1. Go to Settings > Automations
# 2. Click "Create automation" and choose "Create new automation"
# 3. Open the ⋮ menu and switch to "Edit in YAML" view
# 4. Copy the YAML below and paste it into the YAML editor (replacing the existing YAML)
# 5. Switch back to "Edit in visual editor" view
# 6. Click "When something changes" entry and select your Hue light(s).
#    Tip: search for "light" to filter the entities.
# 7. Click "Set turn-on behavior" entry and edit the brightness/CT settings.
#    Don't touch the Targets section.
# 8. Click "Save"
#
# Technical details if you're curious:
#
# Each light turning off triggers a parallel run of the automation. If you add
# more than 10 lights to this automation, increase "max: 10" accordingly.
#
# Hue lights take 400ms to turn off, hence the 1s delay to hold color temperature
# steady until the light dims to zero.


alias: Update Hue lights after turning off
description: >
  When lights turn off, set brightness and/or color temperature for next turn-on.
triggers:
  - trigger: state
    entity_id: []
    from:
      - "on"
    to:
      - "off"
    for:
      hours: 0
      minutes: 0
      seconds: 1
actions:
  - action: hue_dimmer.set_attributes
    target:
      entity_id: "{{ trigger.entity_id }}"
    data:
      max_brightness: 80
      min_brightness: 25
      alias: Set turn-on behavior for the lights
mode: parallel
max: 10
